djangotutorial/polls/urls.py
from django.urls import path 

from . import views 

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),

]

djangotutorial/real_live_rpg/urls.py
from django.urls import path 

from . import views 

app_name = "rpg"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("create/", views.create_skill, name="create_skill"),
    path("delete-skill/<int:skill_id>/", views.delete_skill, name="delete_skill"),
    #
    path("train/<int:skill_id>/", views.train_skill, name="train"),
    path("train/<int:pk>/edit/", views.edit_training_session, name="edit_training_session"),
    path("train/<int:pk>/remove-session/", views.remove_training_session, name="remove_training_session"),
]

djangotutorial/sitename/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views 

#

urlpatterns = [
    path("", views.IndexView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
    path('rbg/', include("real_live_rpg.urls")),

    # path("", include('form_app.urls'))

]

djangotutorial/templates/magic/basics.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <!--  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>

<body>
    <nav class="navbar bg-primary navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:index' %}">Polls</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'rpg:index' %}">RPG</a>
                    </li>
                    <!--
                     <li class="nav-item">
                        <a class="nav-link" href="% url 'behavior_strategies:index' %">Behavioral Strategies</a>
                    </li>
                     -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown link
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container" id="content">
        <div class="row">
            <div class="col-12 mt-3 mb-5">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    <!--  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!--  -->
</body>

</html>

djangotutorial/templates/magic/index.html
{% extends "magic/basics.html" %}

{% block content %}
<div class="row">
    <div class="col-12">
        <h1>Test the world</h1>
        <p>Was surprisingly tricky</p>
    </div>
</div>

{% endblock %}
<!--  -->